class HTMLSummary:
    
    def __init__(self, summary_name: str):
        '''
            Represent HTML for
            generate file later.
        '''
        self.content: str = f'<!DOCTYPE html><head><meta charset = "utf-8" /><meta name = "viewport" content = "height = device-height, width = device-width, initial-scale = 1.0" /><title>{summary_name}</title><style>_BRACKETS_STYLE_PARENTHESES_STYLE_QUOTE_STYLE_ITEM_STYLE</style</head><body>CONTENT</body></html>'

    def add_text(self, logs: str):
        '''
            Change Empty Content By Text
            Generated for the script.
        '''    
        self.content = self.content.replace('CONTENT', logs)
        
    def hightlight(self, brackets_properties: str, parentheses_properties: str, quotation_properties: str, list_items_properties: str):
        '''
            Use CSS color diferentiation for each part of summary generated by
            script and delimit text with that text in span with CSS class
            when found it in content.
        '''
        for TEMPLATE in [
                            ('_BRACKETS_STYLE', '.brackets', brackets_properties), ('_QUOTE_STYLE', 'quote', quotation_properties), 
                            ('_PARENTHESES_STYLE', '.parenth', parentheses_properties), ('_ITEM_STYLE', '.item', list_items_properties)
                        ]:
            # Load Styles without duplicates self.content assignation code
            self.content = self.content.replace(TEMPLATE[0], TEMPLATE[1] + '{' + TEMPLATE[2] + '}')
        # Change In Code Between <body> tags each text with span with class
        for SYMBOL in   [
                            ('[', '<span class = "brackets">['), (']', ']</span>'),
                            ('(', '<span class = "parenth">('), (')', ')</span>'),
                            ("'", "<span class>'</span>")
                        ]:
            # The Same Pattern Design That Befor To Not Duplicate Same Code
            self.content = self.content.replace(SYMBOL[0], SYMBOL[1])
        
    def save(self, file_name: str):
        '''
            Give Name and Generate HTML file.
        '''
        document = open(f'{file_name}.html', 'w')

        document.write(self.content)

        document.close()